#!/usr/bin/env python
"""S1.2 controller: turn θ (`data/plan/theta*.json`) into actions.

Two modes, because they answer different questions:

  --mode theta    everything comes from θ: a priority unit policy (act on the tile you
                  stand on when it needs work, otherwise walk to the nearest tile that
                  does) plus the θ market schedule.  This is the S1 target agent.
  --mode hybrid   the MARKET comes from θ and the unit actions come from the reference
                  trace of the same seed.  A diagnostic: it separates "can θ carry the
                  market" from "can θ carry the routing", which the S1 residual table
                  needs, and it is cheap.

θ market semantics: `sell["<day>|<item>"]` is the list of lots the plan wants sold that
day; the controller offers them at the day's first `len(lots)` hours (one lot per hour,
merged into one order per item per hour), gated by `price_gate[item]` (do not sell below
the lowest price the reference ever accepted).  `buy_feed["<day>|<item>"]`,
`buy_animal[day]`, `hire[day]` are issued at the day's first hour.

Usage:
  .venv/bin/python scripts/plan_runtime.py --theta data/plan/theta-9000.json \
      --mode hybrid --trace data/trace/wool_drain1_outerprem-9000 --out data/plan/agent-hybrid-9000.py
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

TEMPLATE = '''"""θ-derived agent (mode={mode}, θ={theta_path}).  Generated by scripts/plan_runtime.py."""
import json as _json

# ---- runtime liveness self-check -------------------------------------------
# Three times now a generated agent has been measured while inert or frozen (the
# mode-dispatch ordering bug raised on every step and the harness fallback left the
# agent sitting on its starting money, producing a plausible-looking, parameter- and
# behaviour-independent curve).  A generated agent must be impossible to measure by
# accident, so it audits itself and shouts.
_LIVE = {{"money0": None, "steps": 0, "farmer_ops": 0, "noop_units": 0, "units": 0,
         "mkt_ops": 0, "violations": []}}


def _audit(observation, act, unit_noop):
    s = int(observation["step"])
    if _LIVE["money0"] is None:
        _LIVE["money0"] = float(observation["farms"][int(observation["player"])]["money"])
    _LIVE["steps"] += 1
    fr = act.get("farmer") or ["PASS"]
    if fr and fr[0] != "PASS":
        _LIVE["farmer_ops"] += 1
    _LIVE["units"] += 1 + len(act.get("hands") or [])
    _LIVE["noop_units"] += int(unit_noop)
    _LIVE["mkt_ops"] += len(act.get("market") or [])
    if s >= 719:
        money = float(observation["farms"][int(observation["player"])]["money"])
        if money == _LIVE["money0"]:
            _LIVE["violations"].append("FROZEN: money unchanged from start")
        if _LIVE["farmer_ops"] == 0:
            _LIVE["violations"].append("INERT: no farmer op ever issued")
        if _LIVE["mkt_ops"] == 0:
            _LIVE["violations"].append("INERT: no market op ever issued")
        rate = _LIVE["noop_units"] / max(1, _LIVE["units"])
        if rate > 0.9:
            _LIVE["violations"].append(f"INERT: {{100*rate:.0f}}% of unit actions were no-ops")
        print("LIVENESS", _json.dumps({{k: _LIVE[k] for k in
              ("steps", "money0", "farmer_ops", "units", "noop_units", "mkt_ops")}}),
              "violations", _LIVE["violations"], flush=True)
        mean_steps = (_SCHED["steps"] / max(1, _SCHED["started"])) if "_SCHED" in globals() else 0
        print("SCHEDULER", _json.dumps(dict(_SCHED, mean_steps_per_assignment=round(mean_steps, 1))),
              flush=True)
        if _LIVE["violations"]:
            raise RuntimeError("generated agent failed its liveness audit: "
                               + "; ".join(_LIVE["violations"]))

THETA = _json.loads(r"""{theta_json}""")
TRACE_UNITS = _json.loads(r"""{units_json}""")
MODE = "{mode}"
MAX_ORDERS = 10


def _hour_of(step):
    return int(step) % 24


SEED_COST = {{"WHEAT": 10, "CARROT": 20, "TOMATO": 50, "STRAWBERRY": 100, "MELON": 80}}
ANIMAL_COST = {{"GOOSE": 300, "COW": 400, "SHEEP": 500}}
LAND_COST = (1000, 2000, 4000)


def _fib(n):
    a, b = 1, 1
    for _ in range(n):
        a, b = b, a + b
    return a


_SEED_RESERVE = {{"day": -1, "remaining": 0.0}}


def _seed_reserve_for_day(day):
    """Seed money the day's plan still needs: the plan's own BUY_SEED ops are reserved
    before hires/animals/land, so the first planting day cannot be starved (defect 2)."""
    if _SEED_RESERVE["day"] != day:
        total = 0.0
        for e in (THETA.get("market_program") or {{}}).get(str(day)) or []:
            for op in e.get("ops") or []:
                if op and op[0] == "BUY_SEED" and len(op) > 2:
                    total += max(0, int(op[2])) * SEED_COST.get(op[1], 100)
        _SEED_RESERVE["day"] = day
        _SEED_RESERVE["remaining"] = total
    return _SEED_RESERVE["remaining"]


def _market_cashgated(obs, step):
    """Ordered, cash-gated replay of the inferred program for this hour.

    The ops are replayed in their recorded order and each BUY is gated on the cash
    actually available at that point, crediting the proceeds of the SELLs that precede it
    in the same step -- which is how the engine's own slot order funds the champion's
    land/hire/seed purchases.
    """
    day, hour = int(step) // 24, int(step) % 24
    entries = (THETA.get("market_program") or {{}}).get(str(day)) or []
    player = int(obs["player"])
    prices = obs["market"]["prices"]
    farm = obs["farms"][player]
    out = []
    for e in entries:
        if int(e.get("hour", -1)) != hour:
            continue
        cash = float(farm.get("money", 0) or 0)
        quads = len(list(farm.get("unlocked_quadrants") or []) or [])
        hires = int(farm.get("hires_today", 0) or 0)
        reserve = _seed_reserve_for_day(day)
        for op in e.get("ops") or []:
            if not op:
                continue
            kind = op[0]
            if kind == "SELL":
                n = max(0, int(op[2])) if len(op) > 2 else 0
                cash += n * float(prices.get(op[1], 0) or 0)
                out.append(list(op))
            elif kind == "HIRE":
                cost = _fib(hires)
                if cash - reserve >= cost:
                    cash -= cost
                    hires += 1
                    out.append(["HIRE"])
            elif kind == "BUY_LAND":
                if quads - 1 < len(LAND_COST):
                    cost = LAND_COST[quads - 1]
                    if cash - reserve >= cost:
                        cash -= cost
                        quads += 1
                        out.append(["BUY_LAND"])
            elif kind in ("BUY_SEED", "BUY_PRODUCT", "BUY_ANIMAL"):
                n = max(0, int(op[2])) if len(op) > 2 else 0
                if kind == "BUY_SEED":
                    unit = SEED_COST.get(op[1], 100)
                elif kind == "BUY_ANIMAL":
                    unit = ANIMAL_COST.get(op[1], 500)
                else:
                    unit = float(prices.get(op[1], 0) or 0)
                cost = n * unit
                if kind == "BUY_SEED":
                    if n and cash >= cost:
                        cash -= cost
                        _SEED_RESERVE["remaining"] = max(0.0, reserve - cost)
                        reserve = _SEED_RESERVE["remaining"]
                        out.append(list(op))
                elif n and cash - reserve >= cost:
                    cash -= cost
                    out.append(list(op))
    # forward sales: the plan's hours are the champion's; our production arrives at different
    # times, so sell what we already hold (drain-keyed, above the plan's own price gate).
    planned = {{o[1] for o in out if o and o[0] == "SELL"}}
    for item, floor in (THETA.get("price_gate") or {{}}).items():
        if item in planned:
            continue
        have = int((obs["private"].get("shed") or {{}}).get(item, 0))
        if have <= 0:
            continue
        if int(prices.get(item, 0) or 0) < max(2, int(floor or 0)):
            continue
        out.append(["SELL", item, min(have, 2)])
    return out[:MAX_ORDERS]


def _market(obs, step):
    day = int(step) // 24
    hour = _hour_of(step)
    out = []
    if hour == 0:
        for key, n in (THETA.get("buy_feed") or {{}}).items():
            d, item = key.split("|")
            if int(d) == day and n:
                out.append(["BUY_PRODUCT", item, int(n)])
        for animal, n in (THETA.get("buy_animal", {{}}).get(str(day)) or {{}}).items():
            if n:
                out.append(["BUY_ANIMAL", animal, int(n)])
        for _ in range(int((THETA.get("hire", {{}}) or {{}}).get(str(day), 0) or 0)):
            out.append(["HIRE"])
    if hour == 0:
        for key, n in (THETA.get("buy_seed") or {{}}).items():
            d, crop = key.split("|")
            if int(d) == day and n:
                out.append(["BUY_SEED", crop, int(n)])
    if hour == 0:
        for land_day in (THETA.get("land_days") or []):
            if int(land_day) == day:
                out.append(["BUY_LAND"])
                break
    for item, floor in (THETA.get("price_gate") or {{}}).items():
        lots = (THETA.get("sell") or {{}}).get(f"{{day}}|{{item}}") or []
        if hour < len(lots) and int(obs["market"]["prices"].get(item, 0)) >= int(floor):
            q = int(lots[hour])
            if q > 0:
                out.append(["SELL", item, q])
    # forward sales: the plan's hours are the champion's; our production arrives at different
    # times, so sell what we already hold (drain-keyed, above the plan's own price gate).
    planned = {{o[1] for o in out if o and o[0] == "SELL"}}
    for item, floor in (THETA.get("price_gate") or {{}}).items():
        if item in planned:
            continue
        have = int((obs["private"].get("shed") or {{}}).get(item, 0))
        if have <= 0:
            continue
        if int(prices.get(item, 0) or 0) < max(2, int(floor or 0)):
            continue
        out.append(["SELL", item, min(have, 2)])
    return out[:MAX_ORDERS]


def _unit(obs, idx):
    """State-following unit policy: work the tile you stand on, else walk to the nearest
    job.  Jobs come from θ's own plan (plant/water/fert/harvest/build/feed/care/collect/
    place) with a fixed priority order, so it never follows the tape.

    Priority: HARVEST (income) > FEED/CARE/COLLECT (animals) > WATER > FERTILIZE >
    PLANT > BUILD > PLACE > shed choreography > walk to the nearest job.
    """
    farm = obs["farms"][obs["player"]]
    pos = list(farm["farmer"]) if idx == 0 else list(farm["hands"][idx - 1])
    x, y = int(pos[0]), int(pos[1])
    tiles = farm["tiles"]
    board = len(tiles)
    priv = obs["private"]
    invs = priv.get("inventories") or [{{}}]
    inv = invs[idx] if idx < len(invs) else {{}}
    shed = priv.get("shed") or {{}}
    seeds = priv.get("seeds") or {{}}
    day = int(obs["step"]) // 24
    tile = tiles[y][x]
    carry = sum(max(0, int(v)) for v in (inv or {{}}).values())
    adj = x in (board // 2 - 1, board // 2) and y in (board // 2 - 1, board // 2)
    plan_build = (THETA.get("build") or {{}}).get(str(day)) or {{}}

    def plant_crop():
        for crop, n in (seeds or {{}}).items():
            if int(n) > 0 and crop in ("WHEAT", "CARROT", "TOMATO", "STRAWBERRY", "MELON"):
                return ["PLANT", crop]
        return None

    def job(tx, ty):
        t = tiles[ty][tx]
        if not isinstance(t, dict):
            if t is None and any(int(v) > 0 for v in (seeds or {{}}).values()):
                return "PLANT"
            if t is None and (int(shed.get("GOOSE", 0)) > 0 or int(shed.get("COW", 0)) > 0
                              or int(shed.get("SHEEP", 0)) > 0):
                return "BUILD" if plan_build else None
            return None
        kind = t.get("kind")
        if kind == "PLANT":
            if int(t.get("yield_units", 0)) > 0:
                return "HARVEST"
            if not t.get("watered_today"):
                return "WATER"
            return None
        if t.get("animal"):
            if not t.get("fed_today") and int(shed.get("WHEAT", 0)) > 0:
                return "FEED"
            if not t.get("cared_today"):
                return "CARE"
            if t.get("fertilizer_available"):
                return "COLLECT_FERTILIZER"
            return None
        if kind in ("COOP", "PASTURE") and t.get("animal") is None:
            want = "GOOSE" if kind == "COOP" else ("COW" if int(shed.get("COW", 0)) > 0
                                                   else "SHEEP")
            if int(inv.get(want, 0)) > 0:
                return "PLACE"
            if int(shed.get(want, 0)) > 0 and not carry:
                return "PICKUP"
            return None
        return None

    def animal_in_hand():
        for a in ("GOOSE", "COW", "SHEEP"):
            if int((inv or {{}}).get(a, 0)) > 0:
                return a
        return None

    def pen_target():
        """Where should a carried animal go?  Empty matching pen, else a build site."""
        want = animal_in_hand()
        if not want:
            return None
        structure = "COOP" if want == "GOOSE" else "PASTURE"
        for ty2 in range(board):
            for tx2 in range(board):
                t2 = tiles[ty2][tx2]
                if (isinstance(t2, dict) and t2.get("kind") == structure
                        and t2.get("animal") is None and (tx2, ty2) != (x, y)):
                    return (tx2, ty2, "PLACE")
        if plan_build:
            for ty2 in range(board):
                for tx2 in range(board):
                    if tiles[ty2][tx2] is None and (tx2, ty2) != (x, y):
                        return (tx2, ty2, "BUILD")
        return None

    # A carried animal has a DESTINATION, so it must be carried there, never dropped
    # just because the unit is still shed-adjacent (this was the 837/596 ping-pong).
    _animal = animal_in_hand()
    if _animal:
        tgt = pen_target()
        if tgt:
            tx2, ty2, what = tgt
            if (tx2, ty2) == (x, y):
                return ["PLACE", _animal] if what == "PLACE" else (
                    ["BUILD_COOP"] if _animal == "GOOSE" else ["BUILD_PASTURE"])
            return _walk(x, y, tx2, ty2)
        if adj:
            return ["DROP"]
    here = None if carry else job(x, y)
    if here:
        if here == "PLANT":
            return plant_crop() or _walk_to_job(x, y, tiles, board, seeds, shed, plan_build)
        if here == "BUILD":
            return ["BUILD_COOP"] if int(shed.get("GOOSE", 0)) > 0 else ["BUILD_PASTURE"]
        if here == "PLACE":
            t = tiles[y][x]
            want = "GOOSE" if t.get("kind") == "COOP" else (
                "COW" if int(inv.get("COW", 0)) > 0 else "SHEEP")
            return ["PLACE", want]
        if here == "PICKUP":
            t = tiles[y][x]
            want = "GOOSE" if t.get("kind") == "COOP" else (
                "COW" if int(shed.get("COW", 0)) > 0 else "SHEEP")
            return ["PICKUP", want]
        return [here]
    if carry and adj:
        return ["DROP"]                    # non-animal cargo (or an animal with no pen)
    if carry and not adj:
        return _walk(x, y, board // 2, board // 2)
    return _walk_to_job(x, y, tiles, board, seeds, shed, plan_build)


def _walk_to_job(x, y, tiles, board, seeds, shed, plan_build):
    best = None
    for ty in range(board):
        for tx in range(board):
            t = tiles[ty][tx]
            score = None
            if isinstance(t, dict):
                kind = t.get("kind")
                if kind == "PLANT":
                    if int(t.get("yield_units", 0)) > 0:
                        score = 0
                    elif not t.get("watered_today"):
                        score = 2
                elif t.get("animal"):
                    if not t.get("fed_today") and int(shed.get("WHEAT", 0)) > 0:
                        score = 1
                    elif not t.get("cared_today"):
                        score = 1
                    elif t.get("fertilizer_available"):
                        score = 3
                elif kind in ("COOP", "PASTURE") and t.get("animal") is None:
                    score = 4
            elif t is None:
                if any(int(v) > 0 for v in (seeds or {{}}).values()):
                    score = 5
                elif plan_build and (int(shed.get("GOOSE", 0)) > 0
                                     or int(shed.get("COW", 0)) > 0
                                     or int(shed.get("SHEEP", 0)) > 0):
                    score = 6
            if score is None:
                continue
            d = abs(tx - x) + abs(ty - y)
            key = (score, d)
            if best is None or key < best[0]:
                best = (key, tx, ty)
    if best is None:
        return ["PASS"]
    _k, tx, ty = best
    if (tx, ty) == (x, y):
        return ["PASS"]
    return _walk(x, y, tx, ty)


# ---- sequenced persistent job scheduler (S2) --------------------------------
# A reactive per-tile priority cannot express a delivery cycle that spans steps (walk to
# shed -> PICKUP -> walk to pen -> PLACE), which left PLACE/COLLECT_FERTILIZER at zero and
# deadlocked the plan's cash path.  Each unit therefore holds a standing assignment with a
# phase, persisted across steps, abandoned only when genuinely blocked or aged out.
_JOB = {{}}
_RESERVED = {{}}      # (x, y) -> unit index holding that target
_SCHED = {{"started": 0, "completed": 0, "abandoned": 0, "steps": 0, "aged": 0}}
JOB_AGE_LIMIT = 60


# Crop table from the engine: non-ongoing crops start at yield_units = 1 AT PLANTING and
# gain one unit per watered day in the bonus window (plus one per fertilised day), so
# harvesting on `yield_units > 0` throws the season's yield away (628 seedling harvests).
CROPS = {{"WHEAT": {{"max_yield_day": 4, "ongoing": False, "max_yield": 6}},
         "CARROT": {{"max_yield_day": 3, "ongoing": False, "max_yield": 4}},
         "MELON": {{"max_yield_day": 12, "ongoing": False, "max_yield": 6}},
         "TOMATO": {{"max_yield_day": 8, "ongoing": True, "max_yield": 4}},
         "STRAWBERRY": {{"max_yield_day": 10, "ongoing": True, "max_yield": 4}}}}
_WEED_RISK = {{"max_unwatered": 0, "at_risk_steps": 0}}


def _needs(tile, shed, day):
    """What does this tile need, if anything?  (returns op or None)"""
    if not isinstance(tile, dict):
        return None
    kind = tile.get("kind")
    if kind == "PLANT":
        # WATER first, always, for a planted unwatered crop: the engine turns a plant into
        # a weed after two consecutive unwatered days, and watering is what creates yield.
        if not tile.get("watered_today"):
            return "WATER"
        cd = CROPS.get(tile.get("crop"), {{}})
        units = int(tile.get("yield_units", 0))
        if cd.get("ongoing"):
            return "HARVEST" if units > 0 else None
        age = int(day) - int(tile.get("planted_day", day))
        if units >= int(cd.get("max_yield", 6)) or age >= int(cd.get("max_yield_day", 4)):
            return "HARVEST"
        return None
    if tile.get("animal"):
        if not tile.get("fed_today") and int(shed.get("WHEAT", 0)) > 0:
            return "FEED"
        if not tile.get("cared_today"):
            return "CARE"
        if tile.get("fertilizer_available"):
            return "COLLECT_FERTILIZER"
        return None
    return None


def _find_pen(tiles, board, animal, avoid=None, reserved=None, idx=None):
    want = "COOP" if animal == "GOOSE" else "PASTURE"
    for ty in range(board):
        for tx in range(board):
            t = tiles[ty][tx]
            if (isinstance(t, dict) and t.get("kind") == want and t.get("animal") is None
                    and (tx, ty) != avoid):
                if reserved is not None and (tx, ty) in reserved and reserved[(tx, ty)] != idx:
                    continue
                return (tx, ty)
    return None


def _find_build_site(tiles, board, avoid=None):
    for ty in range(board):
        for tx in range(board):
            if tiles[ty][tx] is None and (tx, ty) != avoid:
                return (tx, ty)
    return None


# Selection-level aging: the fixed priority order starved the low-priority ops
# (COLLECT_FERTILIZER 0, WATER 0 with work available, 75% assignment abandonment because
# PLANT kept re-issuing).  Every op type now carries a starvation bonus that grows with the
# number of steps since it was last served anywhere on the farm, so no op type can starve.
_LAST_OP = {{}}
_OP_BASE = {{"HARVEST": 0.5, "WATER": 0.0, "FEED": 2.0, "CARE": 2.5,
            "COLLECT_FERTILIZER": 3.0, "PLANT": 4.0, "PICKUP": 5.0}}
STARVE_GAIN = 0.02      # 0.02 per step -> an op starved for 50 steps gains one rank


def _op_score(op, step):
    return _OP_BASE.get(op, 9.0) - STARVE_GAIN * (step - _LAST_OP.get(op, -10 ** 6))


def _pick_job(obs, idx, x, y, tiles, board, shed, seeds, plan_build, step, day):
    """Choose a NEW standing assignment by starvation-scored priority."""
    cands = []

    def add(kind, op, target, **kw):
        d = abs(target[0] - x) + abs(target[1] - y)
        cands.append((_op_score(op, step) + 0.001 * d,
                      dict(kind=kind, op=op, target=target, age=0, **kw)))

    for a in ("COW", "SHEEP", "GOOSE"):
        if int(shed.get(a, 0)) <= 0:
            continue
        pen = _find_pen(tiles, board, a, avoid=(x, y), reserved=_RESERVED, idx=idx)
        site = pen or (_find_build_site(tiles, board, avoid=(x, y)) if plan_build else None)
        if site:
            add("fetch_animal", "PICKUP", site, animal=a)
    crop = next((c for c, n in (seeds or {{}}).items() if int(n) > 0), None)
    if crop:
        site = _find_build_site(tiles, board, avoid=(x, y))
        if site:
            add("plant", "PLANT", site, crop=crop)
    for ty in range(board):
        for tx in range(board):
            op = _needs(tiles[ty][tx], shed, day)
            if op:
                add("work", op, (tx, ty))
    if not cands:
        return None
    cands.sort(key=lambda kv: kv[0])
    return cands[0][1]


def _unit_sched(obs, idx):
    farm = obs["farms"][obs["player"]]
    pos = list(farm["farmer"]) if idx == 0 else list(farm["hands"][idx - 1])
    x, y = int(pos[0]), int(pos[1])
    tiles = farm["tiles"]
    board = len(tiles)
    priv = obs["private"]
    invs = priv.get("inventories") or [{{}}]
    inv = invs[idx] if idx < len(invs) else {{}}
    shed = priv.get("shed") or {{}}
    seeds = priv.get("seeds") or {{}}
    day = int(obs["step"]) // 24
    adj = x in (board // 2 - 1, board // 2) and y in (board // 2 - 1, board // 2)
    tile = tiles[y][x]
    plan_build = (THETA.get("build") or {{}}).get(str(day)) or {{}}
    carry = {{k: int(v) for k, v in (inv or {{}}).items() if int(v) > 0}}
    for _row in tiles:
        for _t in _row:
            if isinstance(_t, dict) and _t.get("kind") == "PLANT":
                _u = int(_t.get("consecutive_unwatered", 0) or 0)
                if _u > _WEED_RISK["max_unwatered"]:
                    _WEED_RISK["max_unwatered"] = _u
                if _u >= 1 and not _t.get("watered_today"):
                    _WEED_RISK["at_risk_steps"] += 1
    animal = next((a for a in ("GOOSE", "COW", "SHEEP") if carry.get(a, 0) > 0), None)
    other = sum(v for k, v in carry.items() if k not in ("GOOSE", "COW", "SHEEP"))

    # ---- carrying phase -----------------------------------------------------
    if animal:
        need = "COOP" if animal == "GOOSE" else "PASTURE"
        pen = _find_pen(tiles, board, animal, avoid=(x, y))
        if isinstance(tile, dict) and tile.get("kind") == need and tile.get("animal") is None:
            pen = (x, y)
        if pen == (x, y):
            _SCHED["completed"] += 1
            _JOB.pop(idx, None)
            if reserved.get((x, y)) == idx:
                del reserved[(x, y)]
            return ["PLACE", animal]
        if pen:
            return _walk(x, y, pen[0], pen[1])
        # No pen exists yet: BUILD one.  This was the missing link -- the scheduler
        # picked animals up, found no structure, and dropped them forever (PLACE 0).
        if tile is None and (plan_build or True):
            return ["BUILD_COOP"] if animal == "GOOSE" else ["BUILD_PASTURE"]
        site = _find_build_site(tiles, board, avoid=(x, y))
        if site:
            return _walk(x, y, site[0], site[1])
        if adj:
            return ["DROP"]
        return _walk(x, y, board // 2, board // 2)
    if other:
        if adj:
            return ["DROP"]
        return _walk(x, y, board // 2, board // 2)

    # ---- no cargo: follow or pick an assignment ----------------------------
    reserved = _RESERVED
    j = _JOB.get(idx)
    if j:
        tgt = j.get("target")
        valid = False
        if j["kind"] == "fetch_animal":
            valid = int(shed.get(j["animal"], 0)) > 0
        elif j["kind"] == "plant":
            valid = (tiles[tgt[1]][tgt[0]] is None
                     and int((seeds or {{}}).get(j["crop"], 0)) > 0)
        elif j["kind"] == "work":
            valid = _needs(tiles[tgt[1]][tgt[0]], shed, day) == j["op"]
        if not valid:
            _SCHED["abandoned"] += 1
            _JOB.pop(idx, None)
            for k, v in list(reserved.items()):
                if v == idx:
                    del reserved[k]
            j = None
        elif j["age"] > JOB_AGE_LIMIT:
            _SCHED["aged"] += 1
            _SCHED["abandoned"] += 1
            _JOB.pop(idx, None)
            j = None
        else:
            j["age"] += 1
            _SCHED["steps"] += 1
            reserved[j["target"]] = idx
    if j is None:
        j = _pick_job(obs, idx, x, y, tiles, board, shed, seeds, plan_build,
                      int(obs["step"]), day)
        if j is None:
            return ["PASS"]
        _JOB[idx] = j
        reserved[j["target"]] = idx
        _SCHED["started"] += 1

    tgt = j["target"]
    if j["kind"] == "fetch_animal":
        if (x, y) == (board // 2, board // 2) or adj:
            _LAST_OP["PICKUP"] = int(obs["step"])
            return ["PICKUP", j["animal"]]
        return _walk(x, y, board // 2, board // 2)
    if (x, y) == tgt:
        if j["kind"] == "plant":
            _LAST_OP["PLANT"] = int(obs["step"])
            return ["PLANT", j["crop"]]
        _LAST_OP[j["op"]] = int(obs["step"])
        _SCHED["completed"] += 1
        _JOB.pop(idx, None)
        if reserved.get(tgt) == idx:
            del reserved[tgt]
        return [j["op"]]
    return _walk(x, y, tgt[0], tgt[1])


def _walk(x, y, tx, ty):
    if x < tx:
        return ["EAST"]
    if x > tx:
        return ["WEST"]
    if y < ty:
        return ["SOUTH"]
    if y > ty:
        return ["NORTH"]
    return ["PASS"]


def agent(observation, configuration=None):
    step = int(observation["step"])
    player = int(observation["player"])
    if MODE in ("hybrid", "cg") and MODE != "full":
        rec = TRACE_UNITS.get(str(step)) or {{}}
        farmer = rec.get("farmer") or ["PASS"]
        hands = rec.get("hands") or []
    else:
        nhands = len(observation["farms"][player].get("hands") or [])
        farmer = _unit_sched(observation, 0)
        hands = [_unit_sched(observation, i + 1) for i in range(nhands)]
    market = (_market_cashgated(observation, step) if MODE in ("cg", "full")
              else _market(observation, step))
    act = {{"farmer": farmer, "hands": hands, "market": market}}
    if MODE in ("full", "theta"):
        _audit(observation, act, _unit_noop(observation, act))
    return act


def _unit_noop(observation, act):
    """Does this step's unit action change anything?  (liveness audit only)"""
    try:
        import copy as _copy
        farm = _copy.deepcopy(observation["farms"][int(observation["player"])])
        priv = _copy.deepcopy(observation["private"])
        before = _json.dumps([farm["tiles"], priv.get("shed"), priv.get("inventories")],
                             sort_keys=True, default=str)
        # the engine applies our action after this call; a purely-relative check is enough:
        # compare the farmer op against PASS and against a walk into a wall
        fr = act.get("farmer") or ["PASS"]
        if fr and fr[0] not in ("PASS", "NORTH", "SOUTH", "EAST", "WEST"):
            return 0
        if fr and fr[0] == "PASS":
            return 1
        return 0
    except Exception:
        return 0
'''


def build(theta_path, mode, trace_dir, out):
    theta = json.loads(Path(theta_path).read_text())
    units = {}
    if mode == "hybrid" and trace_dir:
        for line in Path(trace_dir, "trace.jsonl").read_text().splitlines():
            r = json.loads(line)
            units[str(r["step"])] = {"farmer": r["action"]["farmer"],
                                     "hands": r["action"]["hands"]}
    src = TEMPLATE.format(mode=mode, theta_path=str(theta_path),
                          theta_json=json.dumps(theta), units_json=json.dumps(units))
    compile(src, str(out), "exec")
    Path(out).write_text(src)
    print(f"wrote {out} (mode={mode}, θ fields "
          f"{sum(1 for k in theta if k not in ('source','seed','recovery'))})")
    return out


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--theta", required=True)
    ap.add_argument("--mode", default="hybrid",
                    choices=("hybrid", "theta", "cg", "full"))
    ap.add_argument("--trace", default=None)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    build(a.theta, a.mode, a.trace, a.out)
